name: Release Drafter

on:
  push:
    # workflow will run when commits are pushed to main
    branches:
      - main
  # Optional: workflow will run when PRs are opened or updated
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write
  pull-requests: read

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v7
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
